version: 0.2

phases:
  build:
    commands:
      - echo Building started
      - mvn clean install
    post_build:
      commands:
        - echo Build completed succesfully
artifacts:
  files:
    - target/demo.jar